### PR TITLE
Update arxivwiki link location

### PR DESCRIPTION
**Pull request by marwahaha**
@silky  open to feedback
image

### CODE REVIEW

**Comment by silky** [comment]
Thanks for this @marwahaha ! Looks good; I'll hopefully merge it this weekend.

**Comment by marwahaha** [comment]
Thanks!

**Comment by silky** [comment]
I tried briefly on the weekend, but I need to work out how to spin up a dev environment again; somehow I've lost my old setup.

Having a nix build would help :D https://github.com/scirate/scirate/issues/429

Otherwise, I'll do my best to get to it this week/weekend.

**Comment by silky** [comment]
deployed.

hope it helps you @marwahaha

**Pull request merged**
