### PR TITLE
Big upgrade

### LINKED ISSUE #354: upgrade version of elasticsearch
see #351 and #353 

the elastic log were half of this

### LINKED ISSUE #392: Travis build broken (for a year)
It looks like the CI/CD has been broken for about a year.

Builds all seem to error out with:

`The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .`

See: https://travis-ci.org/github/scirate/scirate/pull_requests for all of them

### LINKED ISSUE #398: update readme/website to properly represent contributors

### PR DESCRIPTION
**Pull request by silky**
- Rails 6
- Ruby 2.6
- Elasticsearch 7
- Smaller font

fixes #354
fixes #392
fixes #398

### CODE REVIEW

**Comment by silky** [comment]
you're welcome @coveralls . i hope you're happy.

**Comment by silky** [comment]
that's right!!!!!

image

**Comment by JacksonBates** [comment]
I love reading your commit messages :laughing:

FWIW, the only other context I hear manifest in is in movies where they have to investigate a plane crash, which seems appropriate

**Comment by silky** [comment]
@JacksonBates - if you have a chance, do you mind trying to get this running on your machine and see if you can see any issues?

i'm planning on doing the actual live upgrade this weekend

**Comment by JacksonBates** [comment]
@silky Just saw this - I'll likely have time either this evening, or tomorrow evening.

**Comment by JacksonBates** [comment]
@silky I upgraded my ruby, elastic etc locally and ran the migration - everything seems to be working smoothly.

Is there anything in particular you want me to look out for? At first glance it all seems to be functioning as expected.

**Comment by silky** [comment]
awesome; no, nothing in particular; thanks for doing that! :)

**Pull request merged**
